ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/laser_library/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/laser_HEPTAGON/inc

obj-$(CONFIG_MSMB_CAMERA) += HPTG_interface.o
obj-$(CONFIG_MSMB_CAMERA) += HPTG_i2c.o
obj-$(CONFIG_MSMB_CAMERA) += HPTG_factory_func.o
obj-$(CONFIG_MSMB_CAMERA) += HPTG_shipping_func.o
obj-$(CONFIG_MSMB_CAMERA) += HPTG_debug.o
obj-$(CONFIG_MSMB_CAMERA) += msm_laser_focus_hepta.o
