ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/laser_library/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/laser_HEPTAGON/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common

obj-$(CONFIG_MSMB_CAMERA) += msm_laser_focus.o
obj-$(CONFIG_MSMB_CAMERA) += laser_verify.o
obj-$(CONFIG_MSMB_CAMERA) += laser_timer.o
obj-$(CONFIG_MSMB_CAMERA) += laser_sysfs.o
obj-$(CONFIG_MSMB_CAMERA) += laser_procfs.o
obj-$(CONFIG_MSMB_CAMERA) += laser_parser.o 
obj-$(CONFIG_MSMB_CAMERA) += laser_mutex.o
obj-$(CONFIG_MSMB_CAMERA) += laser_log.o
obj-$(CONFIG_MSMB_CAMERA) += laser_gpio.o
obj-$(CONFIG_MSMB_CAMERA) += laser_debug.o
obj-$(CONFIG_MSMB_CAMERA) += laser_focus_i2c.o










